### ISSUE TITLE
mac support?

### ISSUE THREAD

**Issue by iphizzle** [Qufyy/obs-scale-to-sound#2]
would love to try this plugin. any chance for mac support?

**Comment by Qufyy** [comment]
I'll try, I don't have macOS anywhere though so no promises

**Comment by Qufyy** [comment]
Ok, [here you go](https://github.com/Qufyy/obs-scale-to-sound/files/7192185/obs-scale-to-sound-0.3.0-macos64.zip). You need to extract it in `/Library/Application Support/obs-studio/plugins` (I think, this is what other plugins do). I have no clue if it works or not, please let me know so that I can release it, thanks

**Comment by Qufyy** [comment]
I went ahead and released it anyway, feel free to create a new issue if there are problems

**Comment by iphizzle** [comment]
sorry, i didn’t get back to you! been really out of it the past week. had a good day the other day which let me do fun obs stuff. 

but i’m trying the plug-in today! thanks so much for taking the time to put it together!!

**Comment by iphizzle** [comment]
could never get it to start working. after installing it and putting it in the right folder with the other plugins, when i go to open obs, mac stops obs from opening and says your plugin cant be verified. it gives me option to cancel or move to trash. i press cancel, and then it opens obs like normal, except i cant find the plugin, so i guess it didn't activate

**Comment by Qufyy** [comment]
> when i go to open obs, mac stops obs from opening and says your plugin cant be verified

I guessed that was going to happen. The executable is not signed, to sign it I would have to pay Apple $100 every year. I can't do that, so you need to enable running unsigned applications (or as Apple calls them, "Applications from unidentified developers") on your Mac, which I have no idea how to do, you need to look it up. Sorry about that.

**Comment by PedroHase** [comment]
Hey, I know I am late to the party, but it's [possible to allow running unsigned binaries on Mac](https://github.molgen.mpg.de/pages/bs/macOSnotes/mac/mac_procs_unsigned.html). Maybe something to add to the readme @dimtpap ?

Basically, after the initial error message appears do the following:
- go to System Preferences > Security & Privacy
- Go to the `General` tab
- There should be following `myFancyBinary was blocked from opening because it is not from an identified developer.` at the bottom
- Click the button `Open it anyway` to allow the binary to be run
- Restart OBS and the Plugin works now :)
